# Generated by Django 3.1.5 on 2021-02-03 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210202_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sDescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='fDiscountPrice',
            new_name='discountPrice',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='fPrice',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sTitle',
            new_name='title',
        ),
    ]
