# Generated by Django 3.1.5 on 2021-02-23 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered',
        ),
    ]
