# Generated by Django 3.1.5 on 2021-03-17 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_orderitem_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='start_date',
        ),
    ]
