# Generated by Django 3.1.5 on 2021-03-20 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20210320_0903'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
