# Generated by Django 3.1.5 on 2021-03-20 03:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0022_useraddress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAddress',
            new_name='CustomerAddress',
        ),
    ]
