# Generated by Django 3.1.5 on 2021-03-20 03:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0023_auto_20210320_0908'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerAddress',
            new_name='UserAddress',
        ),
    ]
