# Generated by Django 3.1.5 on 2021-03-20 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20210320_0909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name_plural': 'UserAddresses'},
        ),
    ]
