# Generated by Django 3.1.5 on 2021-03-20 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_auto_20210320_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='address',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
