# Generated by Django 3.1.5 on 2021-03-20 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_yoyo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Yoyo',
        ),
    ]
