# Generated by Django 3.1.5 on 2021-03-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_auto_20210320_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
