# Generated by Django 3.1.5 on 2021-02-02 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='test-category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgProductImage', models.ImageField(default='default.png', upload_to='productImages/')),
                ('sTitle', models.CharField(max_length=100)),
                ('fPrice', models.FloatField()),
                ('fDiscountPrice', models.FloatField(blank=True, null=True)),
                ('slug', models.SlugField(default='test-product')),
                ('sDescription', models.TextField(default='This is a the place where you have to enter the description about the product. Like the ingredients used how popular the product is')),
                ('category', models.ForeignKey(default='0232', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='website.category')),
            ],
        ),
    ]
