# Generated by Django 3.1.5 on 2021-03-19 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_order_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
