# Generated by Django 3.1.5 on 2021-03-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20210320_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='type',
            field=models.CharField(choices=[('S', 'Shipping'), ('B', 'Billing')], default='S', max_length=1),
        ),
    ]
