# Generated by Django 3.1.5 on 2021-03-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_address_useraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yoyo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hi', models.FloatField()),
            ],
        ),
    ]
