# Generated by Django 3.1.5 on 2021-03-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_address_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_unique_num',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
