# Generated by Django 3.1.5 on 2021-03-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_auto_20210322_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
