# Generated by Django 3.1.5 on 2021-03-22 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_auto_20210322_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discountPrice',
            new_name='discounted_price',
        ),
    ]
