# Generated by Django 3.1.5 on 2021-03-22 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_auto_20210322_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imgProductImage',
            new_name='img',
        ),
    ]
