# Generated by Django 3.1.5 on 2021-03-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_auto_20210322_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_unique_num',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
    ]
